version: '3.4'

services:
  app:
    build: &app-build
      context: ./app
      args:
        - http_proxy
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
