version: '3.4'

services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/go/src/app
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
